integration_service/auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('token/', views.get_token, name='token'),
]

integration_service/integration_service/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import index, actual_index

urlpatterns = [
    path('', index, name='wrong_home'),
    path('you+shall+not+pass/', actual_index, name='home'),
    path('you+shall+not+pass/user/', include('users.form_urls')),
    path('you+shall+not+pass/skill/', include('skills.form_urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('auth/', include('auth.urls')),
    path('api/', include('users.api_urls')),
    path('api/image/', include('images.urls')),
    path('api/locations/', include('locations.urls')),
    path('api/tags/', include('skills.api_urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

integration_service/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.db import models
from django.urls import reverse
from django.utils.deconstruct import deconstructible

from skills.models import Skill


@deconstructible
class LocationValidator(validators.RegexValidator):
    regex = r'^[A-Z][A-Za-z]+(\s[A-Za-z]+)*, [A-Z][A-Za-z]*(\s[A-Za-z]+)*$'
    message = 'Enter a valid location. ' \
              'This value may contain only letters and one comma. ' \
              'Format: "City, Country". First letter must be uppercase.'
    flags = 0


class User(AbstractUser):
    location = models.CharField(
        max_length=100,
        help_text='Required. 100 characters or fewer. '
                  'Format: "City, Country".',
        validators=[LocationValidator()])

    position = models.CharField(max_length=150)
    skills = models.ManyToManyField(Skill, related_name="users", blank=True)

    def get_absolute_url(self):
        return reverse('form_users:detail', args=[str(self.id)])

integration_service/users/forms.py
from django import forms

from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email',
                  'location', 'position', 'skills')

    username = forms.CharField(min_length=9, max_length=35, required=True)
    password = forms.CharField(min_length=6, max_length=30, required=True,
                               widget=forms.PasswordInput())

    def create_user(self):
        new_user = self.save(commit=False)
        new_user.set_password(self.data['password'])
        new_user.save()
        return new_user

integration_service/users/views.py
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView
from django.views.generic.edit import UpdateView, DeleteView
from rest_framework.decorators import api_view
from rest_framework.exceptions import ValidationError

from .forms import UserForm
from .models import User
from .serializers import serialize_user


class UserListView(ListView):
    model = User
    template_name = 'users/list.html'
    queryset = User.objects.all().order_by('id')


class UserDetailView(DetailView):
    model = User
    template_name = 'users/detail.html'


class UserUpdateView(UpdateView):
    model = User
    template_name = 'users/edit.html'
    form_class = UserForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        del form.fields['password']
        return form


class UserDeleteView(DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_url = reverse_lazy('form_users:list')


class UserCreateView(FormView):
    template_name = 'users/create.html'
    form_class = UserForm

    def form_valid(self, user_form):
        new_user = user_form.create_user()
        return render(self.request, 'users/created.html',
                      context={'user': new_user})


@api_view(['GET'])
def get_user_info_by_username(request, username):
    user = get_object_or_404(User, username=username)
    return JsonResponse(serialize_user(user))


@api_view(['GET'])
def get_user_info_by_id(request):
    try:
        user_id = int(request.query_params['StaffId'])
    except KeyError:
        return HttpResponseBadRequest('StaffId is required.')

    user = get_object_or_404(User, id=user_id)
    return JsonResponse(serialize_user(user))


@api_view(['POST'])
def create_user(request):
    user_form = UserForm(request.data)
    if not user_form.is_valid():
        raise ValidationError(user_form.errors)

    user_form.create_user()
    return HttpResponse(status=201)

integration_service/users/templates/users/create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Creating new user{% endblock %}

{% block content %}
  <div class="container">
    <h1>Create new user</h1>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: unset">
        <li class="breadcrumb-item"><a href='{% url 'home' %}'>Home</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:list' %}'>Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ user.username }}</li>
      </ol>
    </nav>
    <hr/>
    <form role="form" method="post">
      {% csrf_token %}

      {{ form.non_field_errors }}
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field|add_class:"form-control"|attr:"required"|add_error_class:"is-invalid" }}
          {% if field.errors %}
            {% for error in field.errors %}
              <div id="{{ field.name }}InvalidFeedback"
                   class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
      {% endfor %}

      <button type="submit" class="btn btn-primary">Create</button>

    </form>
  </div>
{% endblock %}

integration_service/users/templates/users/created.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}User creaded{% endblock %}

{% block content %}
  <div class="container">
    <br/>
    <h1>User <strong>{{ user.username }}</strong> creaded successfully</h1>
    <img src="https://img.icons8.com/clouds/500/000000/checkmark.png"
         alt="success"/>
    <nav class="nav nav-pills">
      <a class="nav-link active"
         href="{% url 'form_users:create' %}">Create one more user</a>
    </nav>
    <nav class="nav nav-pills">
      <a class="nav-link active"
         href="{% url 'home' %}">Home</a>
    </nav>
  </div>
{% endblock %}

integration_service/users/templates/users/delete.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Delete {{ user.name }} user{% endblock %}

{% block content %}
  <div class="container">
    <h1>Delete user</h1>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: unset">
        <li class="breadcrumb-item"><a href='{% url 'home' %}'>Home</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:list' %}'>Users</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:detail' user.id %}'>{{ user.username }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Delete</li>
      </ol>
    </nav>
    <hr/>
    {% include "deletion_form.html" with object_name=user.username %}
  </div>
{% endblock %}

integration_service/users/templates/users/detail.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} user{% endblock %}

{% block content %}
  <div class="container">

    <div class="row justify-content-between  align-items-center">
      <h1 class="col-2">User</h1>
      <ul class="nav">
        <li class="nav-item active">
          <a class="btn btn-outline-secondary" href='{% url 'form_users:edit' user.id %}'>Edit</a>
          <a class="btn btn-outline-danger" href='{% url 'form_users:delete' user.id %}'>Delete</a>
        </li>
      </ul>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: unset">
        <li class="breadcrumb-item"><a href='{% url 'home' %}'>Home</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:list' %}'>Users</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ user.username }}</li>
      </ol>
    </nav>
    <hr/>

    <div class='user-entry'>
      {% include "detail_field.html" with label="Username" content=user.username %}
      {% include "detail_field.html" with label="First name" content=user.first_name %}
      {% include "detail_field.html" with label="Last name" content=user.last_name %}
      {% include "detail_field.html" with label="Email" content=user.email %}
      {% include "detail_field.html" with label="Location" content=user.location %}
      {% include "detail_field.html" with label="Position" content=user.position %}
      <div class="row">
        <h5 class="col-2 text-truncate">Skills</h5>
        <ul class="list-inline col-10">
        {% for skill in user.skills.all %}
          <li class="list-inline-item lead"><a href="{% url 'form_skills:detail' skill.id %}" class="badge badge-info">{{ skill.name }}</a></li>
        {% endfor %}
      </ul>
      </div>

      {% include "detail_field.html" with label="Date joined" content=user.date_joined %}
    </div>

  </div>
{% endblock %}

integration_service/users/templates/users/edit.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Edit {{ user.username }} user{% endblock %}

{% block content %}
  <div class="container">
    <h1>Edit user</h1>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: unset">
        <li class="breadcrumb-item"><a href='{% url 'home' %}'>Home</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:list' %}'>Users</a></li>
        <li class="breadcrumb-item"><a href='{% url 'form_users:detail' user.id %}'>{{ user.username }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Edit</li>
      </ol>
    </nav>
    <hr/>
    {% include "form.html" with form=form button_name="Save" %}
  </div>
{% endblock %}

integration_service/users/templates/users/list.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Users{% endblock %}

{% block content %}
  <div class="container">
    <div class="row justify-content-between  align-items-center">
      <h1 class="col-2">Users</h1>
      <ul class="nav">
        <li class="nav-item active">
          <a class="btn btn-outline-success" href='{% url 'form_users:create' %}'>Create user</a>
        </li>
      </ul>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: unset">
        <li class="breadcrumb-item"><a href='{% url 'home' %}'>Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Users</li>
      </ol>
    </nav>
    <div class="list-group">
      <div class="list-group-item" style="background-color: #F4F6F6">
        <div class="row no-gutters">
          <div class="col-1"><strong>id</strong></div>
          <div class="col-3"><strong>Username</strong></div>
          <div class="col-2"><strong>First name</strong></div>
          <div class="col-2"><strong>Last name</strong></div>
          <div class="col-2"><strong>Location</strong></div>
          <div class="col-2"><strong>Position</strong></div>
        </div>
      </div>
      {% for user in user_list %}
        <a href="{% url 'form_users:detail' user.id %}" class="list-group-item list-group-item-action ">
          <div class="row no-gutters">
            <div class="col-1">{{ user.id }}</div>
            <div class="col-3">{{ user.username }}</div>
            <div class="col-2">{{ user.first_name }}</div>
            <div class="col-2">{{ user.last_name }}</div>
            <div class="col-2">{{ user.location }}</div>
            <div class="col-2">{{ user.position }}</div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}